spring:
  application:
    name: Candidate Onboarding System

  datasource:
    url: jdbc:mysql://localhost:3306/candidate_onboarding_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

  aop:
    auto: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 26rituraj@gmail.com
    password: dwmp hkwk dunm ajen
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#
#    datasource:
#      url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: as
#      password:
#     jpa:
#      hibernate:
#       database-platform: org.hibernate.dialect.H2Dialect
#        ddl-auto: update
